Repository tuk-groupbuy/Groupbuy-FE, pull requests merged in 2025-07, with the labels that each got.

#5 [Fix/#4] 세팅 오류 수정
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_post.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/values/appearances.xml
Labels: FIX 🐞, 김다희

#12 [UI#8] 채팅 화면 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/tuk/tugether/presentation/chat/ChatFragment.kt
  app/src/main/java/com/tuk/tugether/presentation/chat/ChatParticipantFragment.kt
  app/src/main/java/com/tuk/tugether/presentation/chat/ChatRoomActivity.kt
  app/src/main/res/drawable/ic_sample_img.png
  app/src/main/res/drawable/shape_rect_20_blue_300_fill.xml
  app/src/main/res/drawable/shape_rect_8_blue_100_fill.xml
  app/src/main/res/layout/activity_chat_room.xml
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/fragment_chat_participant.xml
  app/src/main/res/layout/item_chat_participant.xml
  app/src/main/res/layout/item_chat_room_list.xml
  app/src/main/res/layout/item_receiver_chat.xml
  app/src/main/res/values/appearances.xml
  app/src/main/res/values/colors.xml
Labels: UI 🖌, 김기찬

#20 [Chore/#19] 패키지 구조 변경
  app/src/main/java/com/tuk/tugether/di/DataSourceModule.kt
  app/src/main/java/com/tuk/tugether/di/DataStoreModule.kt
  app/src/main/java/com/tuk/tugether/di/NetworkModule.kt
  app/src/main/java/com/tuk/tugether/util/network/AuthInterceptor.kt
  app/src/main/java/com/tuk/tugether/util/network/UiState.kt
Labels: CHORE 🎀, 김다희

#34 [Feat/#33] post api 나머지
  app/src/main/java/com/tuk/tugether/data/datasource/PostDataSource.kt
  app/src/main/java/com/tuk/tugether/data/datasourceImpl/PostDataSourceImpl.kt
  app/src/main/java/com/tuk/tugether/data/dto/request/post/CreatePostRequestDto.kt
  app/src/main/java/com/tuk/tugether/data/dto/request/post/UpdatePostRequestDto.kt
  app/src/main/java/com/tuk/tugether/data/dto/response/post/SearchPostResponseDto.kt
  app/src/main/java/com/tuk/tugether/data/repositoryImpl/PostRepositoryImpl.kt
  app/src/main/java/com/tuk/tugether/data/repositoryImpl/post/PostRepositoryImpl.kt
  app/src/main/java/com/tuk/tugether/data/service/PostService.kt
  app/src/main/java/com/tuk/tugether/domain/model/request/post/CreatePostRequestModel.kt
  app/src/main/java/com/tuk/tugether/domain/model/request/post/UpdatePostRequestModel.kt
  app/src/main/java/com/tuk/tugether/domain/model/response/post/SearchPostResponseModel.kt
  app/src/main/java/com/tuk/tugether/domain/repository/PostRepository.kt
  app/src/main/java/com/tuk/tugether/presentation/home/HomeFragment.kt
  app/src/main/java/com/tuk/tugether/presentation/home/HomeViewModel.kt
  app/src/main/java/com/tuk/tugether/presentation/home/adapter/AlarmAdapter.kt
  app/src/main/java/com/tuk/tugether/presentation/home/adapter/AlarmRequestAdapter.kt
  app/src/main/java/com/tuk/tugether/presentation/post/CreatePostFragment.kt
  app/src/main/java/com/tuk/tugether/presentation/post/PostFragment.kt
  app/src/main/java/com/tuk/tugether/presentation/post/PostViewModel.kt
  app/src/main/res/navigation/main_graph.xml
Labels: FEAT ✨, 김다희

#36 [ADD/#35] 채팅방 생성 및 참여 구현
  app/src/main/java/com/tuk/tugether/data/dto/request/chat/CreateChatRequestDto.kt
  app/src/main/java/com/tuk/tugether/data/dto/response/notification/NotificationResponseDto.kt
  app/src/main/java/com/tuk/tugether/domain/model/request/CreateChatRequestModel.kt
  app/src/main/java/com/tuk/tugether/domain/model/response/notification/NotificationResponseModel.kt
  app/src/main/java/com/tuk/tugether/presentation/chat/ChatViewModel.kt
  app/src/main/java/com/tuk/tugether/presentation/home/AlarmFragment.kt
  app/src/main/java/com/tuk/tugether/presentation/home/adapter/AlarmAdapter.kt
  app/src/main/java/com/tuk/tugether/presentation/home/adapter/AlarmRequest.kt
  app/src/main/java/com/tuk/tugether/presentation/home/adapter/AlarmRequestAdapter.kt
  app/src/main/java/com/tuk/tugether/presentation/post/CreatePostFragment.kt
  app/src/main/java/com/tuk/tugether/presentation/post/PostViewModel.kt
Labels: ADD ➕, 김기찬
